apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstack-provider-manager-secrets-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
